export { default as Nav } from "./Components/Nav/Nav";
export { default as Footer } from "./Components/Footer/Footer";
export { default as Contact } from "./Components/Contact/Contact";
export { default as PartnerInHealth } from "./Components/Home Page/PartnerInHealth/PartnerInHealth";
export { default as Consultation } from "./Components/Home Page/Consultation/Consultation";
export { default as WhyUs } from "./Components/Home Page/WhyUs/WhyUs";
export { default as Services } from "./Components/Home Page/Services/Services";
export { default as AboutUs } from "./Components/Home Page/AboutUs/AboutUs";
export { default as FowItWorks } from "./Components/Home Page/HowItWorks/HowItWorks";
export { default as Teeatures } from "./Components/Home Page/Features/Features";
export { default as Hstimonials } from "./Components/Home Page/Testimonials/Testimonials";
export { default as Blog } from "./Components/Home Page/Blog/Blog";
export { default as FAQs } from "./Components/Home Page/FAQs/FAQs";
export { default as About } from "./Components/About Page/AboutUs/About";
export { default as Counter } from "./Components/About Page/Counter/Counter";
export { default as OurMission } from "./Components/About Page/OurMission/OurMission";
export { default as OurVision } from "./Components/About Page/OurVision/OurVision";
export { default as OurValues } from "./Components/About Page/OurValues/OurValues";
export { default as DoctorsTeam } from "./Components/About Page/DoctorsTeam/DoctorsTeam";
export { default as ScrollToTop } from "./Components/ScrollToTop/ScrollToTop";
export { default as BookCall } from "./Components/BookCall/BookCall";
export { default as ServicesPage } from "./Components/Services Page/ServicesPage";
export { default as DoctorsPage } from "./Components/Doctors Page/DoctorsPage";
