export { default as Nav } from "./Components/Nav/Nav";
export { default as Footer } from "./Components/Footer/Footer";
export { default as Contact } from "./Components/Contact/Contact";
export { default as ContactUs } from "./Components/Book Call/ContactUs";
export { default as PartnerInHealth } from "./Components/Home/PartnerInHealth";
export { default as Consultation } from "./Components/Home/Consultation";
export { default as WhyUs } from "./Components/Home/WhyUs";
export { default as Services } from "./Components/Home/Services";
export { default as SingleService } from "./Components/Home/Single service/SingleService";
export { default as AboutUs } from "./Components/Home/AboutUs";
export { default as HowItWorks } from "./Components/Home/HowItWorks";
export { default as Features } from "./Components/Home/Features";
export { default as Testimonials } from "./Components/Home/Testimonials/Testimonials";
export { default as Blog } from "./Components/Home/Blog/Blog";
export { default as SingleBlog } from "./Components/Home/Single Blog/SingelBlog";
export { default as FAQs } from "./Components/Home/FAQs";
export { default as About } from "./Components/About Page/AboutUs/About";
export { default as Counter } from "./Components/About Page/Counter";
export { default as OurMission } from "./Components/About Page/OurMission";
export { default as OurVision } from "./Components/About Page/OurVision";
export { default as OurValues } from "./Components/About Page/OurValues";
export { default as DoctorsTeam } from "./Components/Doctors/DoctorsTeam/DoctorsTeam";
export { default as ScrollToTop } from "./Components/ScrollToTop/ScrollToTop";
export { default as BookCall } from "./Components/Book Call/ContactUs";
export { default as ServicesPage } from "./Components/Home/Services";
export { default as DoctorsPage } from "./Components/Doctors/DoctorsTeam/DoctorsTeam";
export { default as SingleDoctor } from "./Components/Doctors/Single Doctor/SingleDoctor";
